// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetInitialFile returns a playable URL for the startup file, then clears it.
 * @returns {$CancellablePromise<string>}
 */
export function GetInitialFile() {
    return $Call.ByID(641698814);
}

/**
 * GetServerURL returns the base URL of the local file server.
 * @returns {$CancellablePromise<string>}
 */
export function GetServerURL() {
    return $Call.ByID(1510267008);
}

/**
 * GetSettings returns the current settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2484239657).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateActiveColor saves the UI active color to disk.
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function UpdateActiveColor(color) {
    return $Call.ByID(2274726298, color);
}

/**
 * UpdateAlwaysOnTop saves the always-on-top state to disk.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAlwaysOnTop(enabled) {
    return $Call.ByID(359007344, enabled);
}

/**
 * UpdateAppSettings replaces the application configuration and saves to disk.
 * @param {$models.AppSettings} app
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAppSettings(app) {
    return $Call.ByID(2187952533, app);
}

/**
 * UpdateControlSettings replaces the control configuration and saves to disk.
 * @param {$models.ControlSettings} controls
 * @returns {$CancellablePromise<void>}
 */
export function UpdateControlSettings(controls) {
    return $Call.ByID(1477882679, controls);
}

/**
 * UpdateDefaultMode saves the default playback mode to disk.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDefaultMode(mode) {
    return $Call.ByID(2157697809, mode);
}

/**
 * UpdatePlaybackSettings saves volume, mute, thumbnail state and language to disk.
 * @param {number} volume
 * @param {boolean} muted
 * @param {boolean} thumbnailEnabled
 * @param {string} language
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePlaybackSettings(volume, muted, thumbnailEnabled, language) {
    return $Call.ByID(2202615573, volume, muted, thumbnailEnabled, language);
}

/**
 * UpdateVRSettings replaces the VR configuration and saves to disk.
 * @param {$models.VRSettings} vr
 * @returns {$CancellablePromise<void>}
 */
export function UpdateVRSettings(vr) {
    return $Call.ByID(1483391488, vr);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
