// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("singleInstance" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["singleInstance"] = false;
        }
        if (!("alwaysOnTop" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysOnTop"] = false;
        }
        if (!("acceptInactiveClick" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["acceptInactiveClick"] = false;
        }
        if (!("miniProgressBar" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["miniProgressBar"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class ControlSettings {
    /**
     * Creates a new ControlSettings instance.
     * @param {Partial<ControlSettings>} [$$source = {}] - The source object to create the ControlSettings.
     */
    constructor($$source = {}) {
        if (!("clickTimeoutMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clickTimeoutMs"] = 0;
        }
        if (!("doubleClickSeekSecs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doubleClickSeekSecs"] = 0;
        }
        if (!("fastSeekSecs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fastSeekSecs"] = 0;
        }
        if (!("uiHideDelayMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uiHideDelayMs"] = 0;
        }
        if (!("uiHideOnLeaveDelayMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uiHideOnLeaveDelayMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControlSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ControlSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ControlSettings(/** @type {Partial<ControlSettings>} */($$parsedSource));
    }
}

export class PlaybackSettings {
    /**
     * Creates a new PlaybackSettings instance.
     * @param {Partial<PlaybackSettings>} [$$source = {}] - The source object to create the PlaybackSettings.
     */
    constructor($$source = {}) {
        if (!("volume" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["volume"] = 0;
        }
        if (!("muted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["muted"] = false;
        }
        if (!("defaultMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultMode"] = "";
        }
        if (!("thumbnailEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["thumbnailEnabled"] = false;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("activeColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeColor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaybackSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackSettings(/** @type {Partial<PlaybackSettings>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("app" in $$source)) {
            /**
             * @member
             * @type {AppSettings}
             */
            this["app"] = (new AppSettings());
        }
        if (!("vr" in $$source)) {
            /**
             * @member
             * @type {VRSettings}
             */
            this["vr"] = (new VRSettings());
        }
        if (!("playback" in $$source)) {
            /**
             * @member
             * @type {PlaybackSettings}
             */
            this["playback"] = (new PlaybackSettings());
        }
        if (!("controls" in $$source)) {
            /**
             * @member
             * @type {ControlSettings}
             */
            this["controls"] = (new ControlSettings());
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {WindowSettings}
             */
            this["window"] = (new WindowSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        if ("vr" in $$parsedSource) {
            $$parsedSource["vr"] = $$createField1_0($$parsedSource["vr"]);
        }
        if ("playback" in $$parsedSource) {
            $$parsedSource["playback"] = $$createField2_0($$parsedSource["playback"]);
        }
        if ("controls" in $$parsedSource) {
            $$parsedSource["controls"] = $$createField3_0($$parsedSource["controls"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField4_0($$parsedSource["window"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class VROffsetXYZ {
    /**
     * Creates a new VROffsetXYZ instance.
     * @param {Partial<VROffsetXYZ>} [$$source = {}] - The source object to create the VROffsetXYZ.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("z" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["z"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VROffsetXYZ instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VROffsetXYZ}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VROffsetXYZ(/** @type {Partial<VROffsetXYZ>} */($$parsedSource));
    }
}

export class VROffsets {
    /**
     * Creates a new VROffsets instance.
     * @param {Partial<VROffsets>} [$$source = {}] - The source object to create the VROffsets.
     */
    constructor($$source = {}) {
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {VROffsetXYZ}
             */
            this["left"] = (new VROffsetXYZ());
        }
        if (!("right" in $$source)) {
            /**
             * @member
             * @type {VROffsetXYZ}
             */
            this["right"] = (new VROffsetXYZ());
        }
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {VROffsetXYZ}
             */
            this["top"] = (new VROffsetXYZ());
        }
        if (!("bottom" in $$source)) {
            /**
             * @member
             * @type {VROffsetXYZ}
             */
            this["bottom"] = (new VROffsetXYZ());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VROffsets instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VROffsets}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("left" in $$parsedSource) {
            $$parsedSource["left"] = $$createField0_0($$parsedSource["left"]);
        }
        if ("right" in $$parsedSource) {
            $$parsedSource["right"] = $$createField1_0($$parsedSource["right"]);
        }
        if ("top" in $$parsedSource) {
            $$parsedSource["top"] = $$createField2_0($$parsedSource["top"]);
        }
        if ("bottom" in $$parsedSource) {
            $$parsedSource["bottom"] = $$createField3_0($$parsedSource["bottom"]);
        }
        return new VROffsets(/** @type {Partial<VROffsets>} */($$parsedSource));
    }
}

export class VRSettings {
    /**
     * Creates a new VRSettings instance.
     * @param {Partial<VRSettings>} [$$source = {}] - The source object to create the VRSettings.
     */
    constructor($$source = {}) {
        if (!("offsets" in $$source)) {
            /**
             * @member
             * @type {VROffsets}
             */
            this["offsets"] = (new VROffsets());
        }
        if (!("fov" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fov"] = 0;
        }
        if (!("dragSensitivity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dragSensitivity"] = 0;
        }
        if (!("scrollSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scrollSpeed"] = 0;
        }
        if (!("defaultStart" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultStart"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VRSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VRSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("offsets" in $$parsedSource) {
            $$parsedSource["offsets"] = $$createField0_0($$parsedSource["offsets"]);
        }
        return new VRSettings(/** @type {Partial<VRSettings>} */($$parsedSource));
    }
}

export class WindowSettings {
    /**
     * Creates a new WindowSettings instance.
     * @param {Partial<WindowSettings>} [$$source = {}] - The source object to create the WindowSettings.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowSettings(/** @type {Partial<WindowSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AppSettings.createFrom;
const $$createType1 = VRSettings.createFrom;
const $$createType2 = PlaybackSettings.createFrom;
const $$createType3 = ControlSettings.createFrom;
const $$createType4 = WindowSettings.createFrom;
const $$createType5 = VROffsetXYZ.createFrom;
const $$createType6 = VROffsets.createFrom;
